server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskTracker
    username: postgres
    password: "Hkma2304*"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
